add missing cassert import
without this import i am getting that kind of errors while trying to build on android with jsi enabled:
`node_modules/@nozbe/watermelondb/native/android-jsi/src/main/cpp/DatabasePlatformAndroid.cpp:113:5: error: use of undeclared identifier 'assert'`

with this import it works well